# Generated by Django 4.0.5 on 2022-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fakultet_fan_group_kafedra_student_ustoz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
