# Generated by Django 4.0.5 on 2022-06-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_group_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Guruh',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='group',
            new_name='guruh',
        ),
    ]
